version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: fram
      POSTGRES_PASSWORD: fram
      POSTGRES_DB: employeeHierarchy
    ports:
      - "5432:5432"
  employee-hierarchy:
    image: employee-hierarchy
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      TZ: "Asia/Saigon"
      PORT: ":3000"
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: fram
      POSTGRES_PASSWORD: fram
      POSTGRES_DB: employeeHierarchy